name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Compilar no JAVA
      run: mvn compile
      
    - name: Run Program - Java
      run: java -cp target/classes org.example.Main
    
    - name: Git Version
      uses: codacy/git-version@2.4.0
      with:
        release-branch: main
        prefix: QA-
        
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      
    - name: Use the version
      run: |
         echo ${{ steps.version.outputs.version }}
    - name: Use the previous version
      run: |
        echo ${{ steps.version.outputs.previous-version }}
        
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image
      with:
          image: nicolasgs/aula_maven_f
          tags: ${{github.run_number}}
          registry: docker.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKER_USUARIO }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          

